on:
    push:
        branches:
            - master
        paths:
            - 'packages/server/**'
            - 'packages/moleculer-db-adapter-mongoose/**'
            - 'packages/core/**'
            - '.github/workflows/server.yml'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/cache@v3
              id: pnpm-cache
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - uses: pnpm/action-setup@v2.1.0
              with:
                  run_install: true
                  version: 6.26.1

    build-image:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/checkout@v2

            - name: 'docker publish'
              run: |
                  docker build -f build/k8s/docker/DockerfileServer -t shulandmimi/shared-content:server-$GITHUB_SHA .
                  docker logout
                  echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
                  docker push shulandmimi/shared-content:server-$GITHUB_SHA

    deploy:
        runs-on: ubuntu-latest
        needs: [build, build-image]
        steps:
            - uses: actions/checkout@v2
            - name: '部署'
              run: |
                  sudo echo ${{ secrets.KUBE_HOST }} apiserver.master | sudo tee -a /etc/hosts
                  sed -i -e "s/image: .*$/image: shulandmimi\/shared-content:server-$GITHUB_SHA/" build/k8s/server.yml
                  cat build/k8s/server.yml
            - name: '配置注入'
              run: |
                  mkdir ~/.kube
                  echo -e "${{ secrets.KUBE_CONFIG }}" | base64 -d >> ~/.kube/config
            - name: '更新'
              run: kubectl apply -f ./build/k8s/server.yml
